# Generated by Django 4.1.3 on 2022-11-15 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Authentication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('second_name', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=150)),
                ('bio', models.TextField(blank=True)),
                ('profileimg', models.ImageField(default='blank-prof.jpg', upload_to='profileimg')),
                ('location', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
