# Generated by Django 4.1.3 on 2022-11-16 11:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('images_video', models.FileField(blank=True, null=True, upload_to='postedfiles')),
            ],
        ),
        migrations.RenameModel(
            old_name='Authentication',
            new_name='Profile',
        ),
    ]
