# Generated by Django 4.1.3 on 2022-11-23 10:42

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tweets_rename_authentication_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('user', models.CharField(max_length=200)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('posts_image', models.ImageField(upload_to='post_images')),
                ('caption', models.TextField()),
                ('no_of_likes', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='Tweets',
        ),
    ]
