# Generated by Django 4.1.3 on 2022-11-24 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_posts_delete_tweets'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
