# Generated by Django 4.1.3 on 2022-12-05 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='post_commented',
            field=models.CharField(default='post_id', max_length=500),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
