# Generated by Django 4.1.3 on 2022-12-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_comments_post_commented_alter_comments_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_no_comments',
            field=models.IntegerField(default=0),
        ),
    ]
