# Generated by Django 4.1.4 on 2023-01-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_post_post_no_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='posts_image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images'),
        ),
    ]
